spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/sm_db


mybatis-plus:
  type-aliases-package: com.example.stu
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
      table-prefix: news_



jwt:
  token:
    tokenExpiration: 120
    tokenSignKey: headlaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaine123456